# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-04 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='programming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frameworks', to='programming.Programming'),
        ),
    ]
