# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-05 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import programming.models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0002_auto_20170704_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programming',
            name='photo',
            field=models.ImageField(blank=True, default=b'nf.jpg', null=True, upload_to=programming.models.file_upload),
        ),
    ]
